# Generated by Django 3.1.1 on 2020-10-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myname', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=100)),
                ('bio1', models.CharField(max_length=100)),
                ('pic', models.ImageField(default='', upload_to='image/')),
                ('pic1', models.ImageField(default='', upload_to='image/')),
            ],
        ),
    ]
