# Generated by Django 3.1.1 on 2020-10-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutpic', models.ImageField(default='', upload_to='image/')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('completed_projects', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='my_home',
            old_name='pic',
            new_name='homepic',
        ),
        migrations.RenameField(
            model_name='my_home',
            old_name='pic1',
            new_name='homepic1',
        ),
    ]
