# Generated by Django 3.1.1 on 2020-10-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0002_auto_20201018_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Servicetext', models.CharField(max_length=100)),
                ('Service1', models.CharField(max_length=100)),
                ('Service2', models.CharField(max_length=100)),
                ('Service3', models.CharField(max_length=100)),
                ('Service4', models.CharField(max_length=100)),
                ('Service5', models.CharField(max_length=100)),
                ('Service6', models.CharField(max_length=100)),
            ],
        ),
    ]
