# Generated by Django 3.1.1 on 2020-10-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0003_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_date1', models.CharField(max_length=100)),
                ('resume_title1', models.CharField(max_length=100)),
                ('resume_span1', models.CharField(max_length=100)),
                ('resume_text1', models.CharField(max_length=100)),
                ('resume_date2', models.CharField(max_length=100)),
                ('resume_title2', models.CharField(max_length=100)),
                ('resume_span2', models.CharField(max_length=100)),
                ('resume_text2', models.CharField(max_length=100)),
                ('resume_date3', models.CharField(max_length=100)),
                ('resume_title3', models.CharField(max_length=100)),
                ('resume_span3', models.CharField(max_length=100)),
                ('resume_text3', models.CharField(max_length=100)),
                ('resume_date4', models.CharField(max_length=100)),
                ('resume_title4', models.CharField(max_length=100)),
                ('resume_span4', models.CharField(max_length=100)),
                ('resume_text4', models.CharField(max_length=100)),
                ('resume_date5', models.CharField(max_length=100)),
                ('resume_title5', models.CharField(max_length=100)),
                ('resume_span5', models.CharField(max_length=100)),
                ('resume_text5', models.CharField(max_length=100)),
                ('resume_date6', models.CharField(max_length=100)),
                ('resume_title6', models.CharField(max_length=100)),
                ('resume_span6', models.CharField(max_length=100)),
                ('resume_text6', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_text1', models.CharField(max_length=100)),
                ('skill_span1', models.CharField(max_length=100)),
                ('skill_num1', models.CharField(max_length=10)),
                ('skill_span2', models.CharField(max_length=100)),
                ('skill_num2', models.CharField(max_length=10)),
                ('skill_span3', models.CharField(max_length=100)),
                ('skill_num3', models.CharField(max_length=10)),
                ('skill_span4', models.CharField(max_length=100)),
                ('skill_num4', models.CharField(max_length=10)),
            ],
        ),
    ]
