# Generated by Django 3.1.1 on 2020-10-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0004_resume_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_date5',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_date6',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_span5',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_span6',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_text5',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_text6',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_title5',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_title6',
        ),
    ]
