# Generated by Django 3.1.2 on 2020-10-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0005_auto_20201022_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_text', models.CharField(max_length=100)),
                ('project_1about1', models.CharField(max_length=100)),
                ('project_1about2', models.CharField(max_length=100)),
                ('project_work1', models.CharField(max_length=100)),
                ('project_2about1', models.CharField(max_length=100)),
                ('project_2about2', models.CharField(max_length=100)),
                ('project_work2', models.CharField(max_length=100)),
                ('project_3about1', models.CharField(max_length=100)),
                ('project_3about2', models.CharField(max_length=100)),
                ('project_work3', models.CharField(max_length=100)),
                ('project_4about1', models.CharField(max_length=100)),
                ('project_4about2', models.CharField(max_length=100)),
                ('project_work4', models.CharField(max_length=100)),
                ('project_5about1', models.CharField(max_length=100)),
                ('project_5about2', models.CharField(max_length=100)),
                ('project_work5', models.CharField(max_length=100)),
                ('project_6about1', models.CharField(max_length=100)),
                ('project_6about2', models.CharField(max_length=100)),
                ('project_work6', models.CharField(max_length=100)),
            ],
        ),
    ]
