# Generated by Django 3.1.2 on 2020-10-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0006_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_pic1',
            field=models.ImageField(default='', upload_to='image/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_pic2',
            field=models.ImageField(default='', upload_to='image/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_pic3',
            field=models.ImageField(default='', upload_to='image/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_pic4',
            field=models.ImageField(default='', upload_to='image/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_pic5',
            field=models.ImageField(default='', upload_to='image/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_pic6',
            field=models.ImageField(default='', upload_to='image/'),
        ),
    ]
