# Generated by Django 3.1.2 on 2020-10-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0007_auto_20201022_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headtext', models.CharField(max_length=100)),
                ('date1', models.CharField(max_length=100)),
                ('spantext1', models.CharField(max_length=100)),
                ('text1', models.CharField(max_length=100)),
                ('date2', models.CharField(max_length=100)),
                ('spantext2', models.CharField(max_length=100)),
                ('text2', models.CharField(max_length=100)),
                ('date3', models.CharField(max_length=100)),
                ('spantext3', models.CharField(max_length=100)),
                ('text3', models.CharField(max_length=100)),
                ('awards', models.CharField(max_length=10)),
                ('projects', models.CharField(max_length=10)),
                ('happy', models.CharField(max_length=10)),
            ],
        ),
    ]
