# Generated by Django 3.1.2 on 2020-10-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0009_auto_20201024_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='admin1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='admin2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='admin3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
