# Generated by Django 3.1.2 on 2020-10-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0010_auto_20201024_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='freeheadtext',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='freetext',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
