# Generated by Django 3.1.1 on 2020-10-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0013_auto_20201025_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_1about2',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_2about2',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_3about2',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_4about2',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_5about2',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_6about2',
        ),
        migrations.AddField(
            model_name='my_about',
            name='cv',
            field=models.FileField(default='', null=True, upload_to='file/'),
        ),
    ]
