# Generated by Django 3.1.1 on 2020-10-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0014_auto_20201027_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='cv',
            field=models.FileField(null=True, upload_to='file/'),
        ),
        migrations.AlterField(
            model_name='my_about',
            name='cv',
            field=models.FileField(null=True, upload_to='file/'),
        ),
    ]
