# Generated by Django 3.1.1 on 2020-10-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0015_auto_20201027_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='admin2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='admin3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='date2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='date3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='spantext2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='spantext3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='text3',
        ),
    ]
