# Generated by Django 3.1.1 on 2020-10-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0016_auto_20201029_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='freetext',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
